[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Eirene = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProjectX = "5bc72906-84ee-441a-b1af-482a16c1ccd3"
ROC = "e4f92426-8875-4712-a903-a153c75bec82"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
